apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb
spec:
  addresses:
    - 192.168.60.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dastech.local
  namespace: metallb
spec:
  ipAddressPools:
    - primary-pool