on: push

jobs:
  Build-Docker-Images:
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: repo/image
          tags: v1, latest
          registry: docker.io
          dockerfile: cluster/Grafana/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}